[tool.poetry]
name = "london-drift-detector"
version = "0.1.0"
description = ""
authors = [
    "Przemyslaw Wrona <przemekwrona25@gmail.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.14"
pandas = "^3.0.2"
pyarrow = "^23.0.1"
matplotlib = "^3.10.8"
seaborn = "^0.13.2"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
merge-csvs = "main:merger"
plot-hist = "main:plot_hist"